-- 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회하는 SQL문 작성한다. 
# 보호 기간이 긴 순으로 조회
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC
LIMIT 2;
