-- 코드를 입력하세요
# 여러 개의 DISCOUNT_RATE 중에서 DURATION_TYPE이 30일 이상인 것을 선택해서 계산해야한다.
# SELECT *, (CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) * 30 / 100) AS FEE
SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) * 30 / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CAR.CAR_ID = HIS.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= "2022-11-01" AND START_DATE <= "2022-12-01"
) AND DURATION_TYPE LIKE "30%"
GROUP BY CAR.CAR_ID
HAVING CAR.CAR_TYPE IN ("세단","SUV") 
AND 500000 <= FEE
AND FEE < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;
