WITH RANK_DATA AS(
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNK, MAX(ID) OVER() AS TOTAL
    FROM ECOLI_DATA)
    

SELECT ID, CASE WHEN RNK/TOTAL <= 0.25 THEN 'CRITICAL'
            WHEN RNK/TOTAL <= 0.5 THEN 'HIGH'
            WHEN RNK/TOTAL <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
            END COLONY_NAME
            
FROM RANK_DATA
ORDER BY ID;