-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS "전체주소", CONCAT(SUBSTRING(U.TLNO, 1, 3), '-', SUBSTRING(U.TLNO, 4, 4), '-', SUBSTRING(U.TLNO, 8, 11)) AS "전화번호"
FROM USED_GOODS_USER U 
JOIN USED_GOODS_BOARD B 
ON B.WRITER_ID = U.USER_ID
GROUP BY USER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY USER_ID DESC;