-- 보호소에 들어올 당시에는 중성화 되지 않았지만, 보호소를 나갈 당시에는 중성화된 동물의 아이디
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM (SELECT * 
      FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE "Intact%") I
JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME LIKE "Spayed%" 
OR O.SEX_UPON_OUTCOME LIKE "Neutered%";