# 2022년 4월 13일 취소되지 않은 흉부외과 진료 예약 내역 조회
SELECT APP.APNT_NO, PAT.PT_NAME, PAT.PT_NO, DOC.MCDP_CD, DOC.DR_NAME, APP.APNT_YMD
FROM APPOINTMENT APP
JOIN DOCTOR DOC ON  DOC.DR_ID = APP.MDDR_ID
JOIN PATIENT PAT ON PAT.PT_NO = APP.PT_NO
WHERE APP.APNT_CNCL_YMD IS NULL AND APP.MCDP_CD = 'CS' AND APP.APNT_YMD LIKE '2022-04-13%'
ORDER BY APP.APNT_YMD
