-- 코드를 작성해주세요
-- 희귀도가 RARE인 아이템들의 다음 업그레이드 아이템의 아이템 ID
SELECT B.ITEM_ID, 
       (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID = B.ITEM_ID) AS ITEM_NAME,
       (SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID = B.ITEM_ID) AS RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE A.RARITY = 'RARE'
ORDER BY B.ITEM_ID DESC;
