-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF left join ICECREAM_INFO
on FIRST_HALF.flavor = ICECREAM_INFO.flavor
WHERE FIRST_HALF.TOTAL_ORDER > 3000 and ICECREAM_INFO.INGREDIENT_TYPE like 'fruit_based'
order by TOTAL_ORDER DESC;