-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', FI.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE FI 
LEFT JOIN USED_GOODS_BOARD BO 
ON FI.BOARD_ID = BO.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;